/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as FreightRouteImport } from './routes/freight'
import { Route as AirportsRouteImport } from './routes/airports'
import { Route as IndexRouteImport } from './routes/index'

const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightRoute = FreightRouteImport.update({
  id: '/freight',
  path: '/freight',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportsRoute = AirportsRouteImport.update({
  id: '/airports',
  path: '/airports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airports': typeof AirportsRoute
  '/freight': typeof FreightRoute
  '/routes': typeof RoutesRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airports': typeof AirportsRoute
  '/freight': typeof FreightRoute
  '/routes': typeof RoutesRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airports': typeof AirportsRoute
  '/freight': typeof FreightRoute
  '/routes': typeof RoutesRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/airports' | '/freight' | '/routes' | '/scenarios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/airports' | '/freight' | '/routes' | '/scenarios'
  id: '__root__' | '/' | '/airports' | '/freight' | '/routes' | '/scenarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirportsRoute: typeof AirportsRoute
  FreightRoute: typeof FreightRoute
  RoutesRoute: typeof RoutesRoute
  ScenariosRoute: typeof ScenariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight': {
      id: '/freight'
      path: '/freight'
      fullPath: '/freight'
      preLoaderRoute: typeof FreightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airports': {
      id: '/airports'
      path: '/airports'
      fullPath: '/airports'
      preLoaderRoute: typeof AirportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirportsRoute: AirportsRoute,
  FreightRoute: FreightRoute,
  RoutesRoute: RoutesRoute,
  ScenariosRoute: ScenariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
